import { AppTheme } from '../ThemeContext';

export const luxuryFlatTheme: AppTheme = {
  name: 'Luxury Flat',
  colors: {
    primary: '#000000',
    secondary: '#0A0A0A',
    accent: '#000000',
    accentLight: '#1A1A1A',
    background: '#000000',
    surface: '#000000',
    surfaceBorder: '#222222',
    textPrimary: '#FFFFFF',
    textSecondary: '#888888',
    textOnPrimary: '#FFFFFF',
    textOnAccent: '#FFFFFF',
    success: '#FFFFFF',
    error: '#FF3B30',
    warning: '#FFFFFF',
    info: '#FFFFFF',
    gray: '#555555',
    grayLight: '#111111',
    grayDark: '#333333',
    border: '#222222',
    disabled: '#333333',
    disabledText: '#666666',
  },
  button: {
    borderRadius: 0,
    paddingVertical: 15,
    paddingHorizontal: 30,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 3,
    textTransform: 'uppercase',
    shineEffect: true,
  },
  card: {
    borderRadius: 0,
    borderWidth: 1,
    shadowOpacity: 0,
  },
  input: {
    borderRadius: 0,
    borderWidth: 1,
    fontSize: 14,
  },
  tab: {
    borderRadius: 0,
    activeBackground: '#FFFFFF',
    activeText: '#000000',
    inactiveBackground: '#0A0A0A',
    inactiveText: '#666666',
  },
  toggle: {
    borderRadius: 99,
    activeBackground: '#FFFFFF',
    inactiveBackground: '#333333',
  },
  typography: {
    fontFamily: 'System',
    headerSize: 22,
    headerWeight: '600',
    headerLetterSpacing: 2,
    bodySize: 14,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  layout: {
    showNearbySection: false,
  },
};
