import { AppTheme } from '../ThemeContext';

export const luxuryFlatTheme: AppTheme = {
  name: 'Luxury Flat',
  colors: {
    primary: '#1E1E1E',
    secondary: '#2A2A2A',
    accent: '#1E1E1E',
    accentLight: '#3A3A3A',
    background: '#FAFAFA',
    surface: '#FFFFFF',
    surfaceBorder: '#E5E5E5',
    textPrimary: '#1E1E1E',
    textSecondary: '#757575',
    textOnPrimary: '#FFFFFF',
    textOnAccent: '#FFFFFF',
    success: '#2E7D32',
    error: '#C62828',
    warning: '#F57F17',
    info: '#1565C0',
    gray: '#B3B3B3',
    grayLight: '#F5F5F5',
    grayDark: '#616161',
    border: '#E5E5E5',
    disabled: '#B3B3B3',
    disabledText: '#FFFFFF',
  },
  button: {
    borderRadius: 0,
    paddingVertical: 15,
    paddingHorizontal: 30,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 2,
    textTransform: 'uppercase',
    shineEffect: true,
  },
  card: {
    borderRadius: 0,
    borderWidth: 1,
    shadowOpacity: 0,
  },
  input: {
    borderRadius: 0,
    borderWidth: 1,
    fontSize: 14,
  },
  tab: {
    borderRadius: 0,
    activeBackground: '#1E1E1E',
    activeText: '#FFFFFF',
    inactiveBackground: '#F5F5F5',
    inactiveText: '#1E1E1E',
  },
  toggle: {
    borderRadius: 99,
    activeBackground: '#1E1E1E',
    inactiveBackground: '#E5E5E5',
  },
  typography: {
    fontFamily: 'System',
    headerSize: 24,
    headerWeight: '700',
    headerLetterSpacing: 1.5,
    bodySize: 14,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};
