import { AppTheme } from '../ThemeContext';

export const defaultTheme: AppTheme = {
  name: 'VIP Classic',
  colors: {
    primary: '#1a1a2e',
    secondary: '#16213e',
    accent: '#c9a84c',
    accentLight: '#e8c97a',
    background: '#f9fafb',
    surface: '#ffffff',
    surfaceBorder: '#e5e7eb',
    textPrimary: '#111827',
    textSecondary: '#6b7280',
    textOnPrimary: '#ffffff',
    textOnAccent: '#1a1a2e',
    success: '#10b981',
    error: '#ef4444',
    warning: '#f59e0b',
    info: '#3b82f6',
    gray: '#9ca3af',
    grayLight: '#f3f4f6',
    grayDark: '#4b5563',
    border: '#e5e7eb',
    disabled: '#d1d5db',
    disabledText: '#9ca3af',
  },
  button: {
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 24,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0,
    textTransform: 'none',
    shineEffect: false,
  },
  card: {
    borderRadius: 12,
    borderWidth: 1,
    shadowOpacity: 0.08,
  },
  input: {
    borderRadius: 8,
    borderWidth: 1,
    fontSize: 15,
  },
  tab: {
    borderRadius: 8,
    activeBackground: '#fefce8',
    activeText: '#c9a84c',
    inactiveBackground: 'transparent',
    inactiveText: '#6b7280',
  },
  toggle: {
    borderRadius: 13,
    activeBackground: '#c9a84c',
    inactiveBackground: '#e5e7eb',
  },
  typography: {
    fontFamily: 'System',
    headerSize: 22,
    headerWeight: '800',
    headerLetterSpacing: 0,
    bodySize: 14,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
};
